# fly.toml app configuration file generated for msgboard88 on 2023-09-07T13:55:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "msgboard88"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
